version: '3'
services:
  # haccp:
  #   image: yokudlela/haccp:latest
  #   environment:
  #     - KEYCLOAK_AUTH_SERVER_URL=http://172.17.0.2:6080/auth
  #   ports:
  #     - '8080:8080'
  mariadb:
    image: mariadb:latest
    environment:
      PROXY_ADDRESS_FORWARDING: 'true'
      MYSQL_ROOT_PASSWORD: yokudlela
  #    MYSQL_DATABASE: keycloak
  #    MYSQL_USER: yokudlela
  #    MYSQL_PASSWORD: yokudlela
    ports:
      - '3306:3306'
    command: mysqld --lower_case_table_names=1
    restart: on-failure
    volumes:
      - ${PWD}/../../disks/sql:/var/lib/mysql
      - ${PWD}/init-db/iam.sql:/docker-entrypoint-initdb.d/1.sql:ro
      - ${PWD}/init-db/haccp-service.sql:/docker-entrypoint-initdb.d/2.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  keycloak:
    image: sleighzy/keycloak:16.1.0-arm64
    ports:
      - '6080:8080'
    environment:
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=iam
      - DB_USER=iam
      - DB_PASSWORD=iam
      - DB_PORT=3306
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=yokudlela
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ${PWD}/realm-export.json:/tmp/example-realm.json
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
  redis:
    image: redis:latest
    ports:
      - '6379:6379'